### ISSUE TITLE
bug/ui: misalignment in user-add dialogue

### ISSUE THREAD

**Issue by m-ildefons** [jecluis/ghd#12]
UI elements in the user-add dialogue are misaligned.

![ghd-misaligned-dialogue](https://user-images.githubusercontent.com/17141774/221592480-21537379-2e1d-45bc-a943-b2d058e5665d.png)

ghd version: https://github.com/jecluis/ghd/releases/download/v0.3.0/ghd
```
$ cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.4 Beta"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4 Beta"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

**Comment by jecluis** [comment]
Seems to be due to viewport size and the dialog stuff not being properly responsive.

**Comment by m-ildefons** [comment]
I'm running i3wm in 4K resolution with an NVidia card, if that makes a difference. I think the popup is not a separate window to i3wm though, but rather an overlaying element in the viewport, so all that shouldn't really be important.

**Comment by jecluis** [comment]
I mean that when the viewport of ghd is small enough width-wise, I also see that happening. Doesn't happen if I enlarge the window. The real problem though is that this shows the form does not adjust to that reality and that needs to be fixed.

**Comment by jecluis** [comment]
fixed on main
