### ISSUE TITLE
ghd: feature request, shortcut for exiting the application

### ISSUE THREAD

**Issue by m-ildefons** [jecluis/ghd#13]
Currently, the only way I have found to exit the application is to send SIGTERM or SIGKILL to the process. This is uncomfortable enough, when starting the application from the terminal, but really not great when starting the application from a launcher, as then I would first have to figure out a PID and then do something like `kill -s SIGTERM $PID`. A key-combination like Ctrl+q to exit the application would be nice.

**Comment by jecluis** [comment]
Instead of a keyboard shortcut, would an "exit" button be acceptable? Not necessarily mutual exclusive though.

**Comment by jecluis** [comment]
for my future me's reference: https://tauri.app/v1/api/js/process/

**Comment by jecluis** [comment]
oh, and this: https://tauri.app/v1/api/js/globalShortcut

**Comment by m-ildefons** [comment]
Yes, an exit button would work too. I found out that it does respond correctly to window-close events, which can be triggered by key-combination on `i3wm`, so this feature request is kind of low priority now. Still it would be nice to have Ctrl+q work.
